---
services:
  prometheus:
    image: prom/prometheus:v3.9.1
    ports:
      - 127.0.0.1:9090:9090
    command: --web.enable-otlp-receiver --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
