---
scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      # We are scraping the prometheus endpoint from the otel
      # collector, not our webserver.
      - targets: ['collector:9090']
